# Generated by Django 4.2.2 on 2023-07-08 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='Título')),
                ('description', models.TextField(null=True, verbose_name='Descrição')),
                ('priority', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], default=0, max_length=1, verbose_name='Prioridade')),
                ('deadline', models.DateTimeField(default=None, null=True, verbose_name='Prazo')),
                ('done', models.BooleanField(default=False, verbose_name='Concluído')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
